In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('../../../data.csv').head()
df

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [4]:
df.dtypes

Duration      int64
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [6]:
df.memory_usage()

Index       132
Duration     40
Pulse        40
Maxpulse     40
Calories     40
dtype: int64

In [8]:
df['Calories']

0    409.1
1    479.0
2    340.0
3    282.4
4    406.0
Name: Calories, dtype: float64

In [11]:
df['Calories']=df['Calories'].astype('float32')
df['Calories']

0    409.100006
1    479.000000
2    340.000000
3    282.399994
4    406.000000
Name: Calories, dtype: float32

In [12]:
df['Calories']

0    409.100006
1    479.000000
2    340.000000
3    282.399994
4    406.000000
Name: Calories, dtype: float32

In [15]:
df=df.astype(
    {
        "Pulse":'int8', 
        "Maxpulse":'int8'
    }
)
df

   Duration  Pulse  Maxpulse    Calories
0        60    110      -126  409.100006
1        60    117      -111  479.000000
2        60    103      -121  340.000000
3        45    109       -81  282.399994
4        45    117      -108  406.000000

In [16]:
df.dtypes

Duration      int64
Pulse          int8
Maxpulse       int8
Calories    float32
dtype: object