In [1]:
import pandas as pd

In [15]:
df=pd.read_csv('../../../data.csv').head()
df

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [4]:
df_copy=df.copy()
df_copy

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [6]:
df_copy.columns

Index(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='str')

In [7]:
df_copy.columns=['duration', 'Puls', 'M_pulse', 'Caloris']

In [8]:
df_copy

   duration  Puls  M_pulse  Caloris
0        60   110      130    409.1
1        60   117      145    479.0
2        60   103      135    340.0
3        45   109      175    282.4
4        45   117      148    406.0

In [9]:
df

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [5]:
df_ref=df
df_ref

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [10]:
df_ref.columns=['duration', 'pulse', 'Max_pulse', 'Caloris']
df_ref

   duration  pulse  Max_pulse  Caloris
0        60    110        130    409.1
1        60    117        145    479.0
2        60    103        135    340.0
3        45    109        175    282.4
4        45    117        148    406.0

In [16]:
df

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [20]:
df.loc[2,'Duration']=50

In [21]:
df

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        50    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [22]:
df.loc[0:2]=100
df

   Duration  Pulse  Maxpulse  Calories
0       100    100       100     100.0
1       100    100       100     100.0
2       100    100       100     100.0
3        45    109       175     282.4
4        45    117       148     406.0

In [24]:
df.loc[0:2,'Pulse']=50
df

   Duration  Pulse  Maxpulse  Calories
0       100     50       100     100.0
1       100     50       100     100.0
2       100     50       100     100.0
3        45    109       175     282.4
4        45    117       148     406.0

In [26]:
df.loc[2,['Duration','Maxpulse']]=90
df

   Duration  Pulse  Maxpulse  Calories
0        80     50        80     100.0
1        80     50        80     100.0
2        90     50        90     100.0
3        45    109       175     282.4
4        45    117       148     406.0

In [34]:
df['Duration']>=80

0     True
1     True
2     True
3    False
4    False
Name: Duration, dtype: bool

In [33]:
df.loc[df['Duration']>=80]

   Duration  Pulse  Maxpulse  Calories
0        80     50        80     100.0
1        80     50        80     100.0
2        90     50        90     100.0