In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('../../../car_data_500.csv').head()
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

# Get Cell Value

In [4]:
df.at[2,'car']

'Audi'

In [5]:
df.at[3,'origin']

'Germany'

In [6]:
df.iat[2,5]

np.int64(3527)

In [7]:
df.loc[2,'car']

'Audi'

In [8]:
df.iloc[2,5]

np.int64(3527)

# Handling Rows

In [11]:
df.loc[2]

car              Audi
MPO              21.3
Cylinder          8.0
Displacement     1943
Horsepower        265
weight           3527
Accelarate        8.3
Model              80
origin          India
Name: 2, dtype: object

In [12]:
df.loc[2]=['audi',21.3,8.0,1943,265,3527,8.3,80,'india']

In [13]:
df.loc[2]

car              audi
MPO              21.3
Cylinder          8.0
Displacement     1943
Horsepower        265
weight           3527
Accelarate        8.3
Model              80
origin          india
Name: 2, dtype: object

In [15]:
df.loc[1:2]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,audi,21.3,8.0,1943,265,3527,8.3,80,india

In [16]:
df.loc[1:2]=[['jaguar',21.3,8.0,1943,265,3527,8.3,80,'us'],['Audi',21.3,8.0,1943,265,3527,8.3,80,'India']]

In [17]:
df.loc[1:2]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
1,jaguar,21.3,8.0,1943,265,3527,8.3,80,us
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India

In [18]:
df.loc[[0,1,3]]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,jaguar,21.3,8.0,1943,265,3527,8.3,80,us
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany

# Handling Columns

In [19]:
df.loc[:,'car']

0       Ford
1     jaguar
2       Audi
3    Hyundai
4       Tata
Name: car, dtype: str

In [20]:
df.loc[:,'Displacement']

0    1823
1    1943
2    1943
3    4498
4    2968
Name: Displacement, dtype: int64

In [21]:
df.loc[:,'origin']

0      Japan
1         us
2      India
3    Germany
4         US
Name: origin, dtype: str

In [22]:
df.loc[:,'origin']='India'

In [23]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,India
1,jaguar,21.3,8.0,1943,265,3527,8.3,80,India
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,India
4,Tata,18.0,6.0,2968,140,2706,7.2,74,India

In [26]:
df.loc[:,['origin','car','MPO']]

  origin      car   MPO
0  India     Ford  20.7
1  India   jaguar  21.3
2  India     Audi  21.3
3  India  Hyundai  11.5
4  India     Tata  18.0

In [29]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,India
1,jaguar,21.3,8.0,1943,265,3527,8.3,80,India
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,India
4,Tata,18.0,6.0,2968,140,2706,7.2,74,India

In [31]:
df.loc[:,'Cylinder':'Accelarate']

   Cylinder  Displacement  Horsepower  weight  Accelarate
0       6.0          1823         247    3374        15.5
1       8.0          1943         265    3527         8.3
2       8.0          1943         265    3527         8.3
3       6.0          4498         196    3317         9.9
4       6.0          2968         140    2706         7.2

# adding Prefix and suffix

In [35]:
df.add_prefix('coln_',axis=0)

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
coln_0,Ford,20.7,6.0,1823,247,3374,15.5,76,India
coln_1,jaguar,21.3,8.0,1943,265,3527,8.3,80,India
coln_2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
coln_3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,India
coln_4,Tata,18.0,6.0,2968,140,2706,7.2,74,India

In [36]:
df.add_suffix('_test',axis=0)

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0_test,Ford,20.7,6.0,1823,247,3374,15.5,76,India
1_test,jaguar,21.3,8.0,1943,265,3527,8.3,80,India
2_test,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3_test,Hyundai,11.5,6.0,4498,196,3317,9.9,77,India
4_test,Tata,18.0,6.0,2968,140,2706,7.2,74,India

In [37]:
df.add_suffix('_test',axis=1)

,car_test,MPO_test,Cylinder_test,Displacement_test,Horsepower_test,weight_test,Accelarate_test,Model_test,origin_test
0,Ford,20.7,6.0,1823,247,3374,15.5,76,India
1,jaguar,21.3,8.0,1943,265,3527,8.3,80,India
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,India
4,Tata,18.0,6.0,2968,140,2706,7.2,74,India

# Row index of min Value Based on Specific Column

In [39]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,India
1,jaguar,21.3,8.0,1943,265,3527,8.3,80,India
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,India
4,Tata,18.0,6.0,2968,140,2706,7.2,74,India

In [40]:
df['Displacement'].idxmin()

0

In [41]:
df['Cylinder'].idxmin()

0

In [43]:
df['weight'].idxmax()

1

In [45]:
df['MPO'].argmax()

np.int64(1)

In [46]:
df['MPO'].argmin()

np.int64(3)