In [1]:
import pandas as pd

In [49]:
df=pd.read_csv('../../../car_data_500.csv').head()
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

# REmove Rows or Columns FRom DF 
- drop  => remove unwanted rows/columns
- pop => we can reuse the removed rows/columns 
- truncate =>

# Drop

In [28]:
df.drop([0,1])

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [6]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [7]:
df=df.drop([0,3])

In [8]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [12]:
df=df.drop(['car'],axis=1)

In [13]:
df

    MPO  Cylinder  Displacement  Horsepower  weight  Accelarate  Model origin
1  17.4       4.0          1793         186    2196        15.9     73     US
2  21.3       8.0          1943         265    3527         8.3     80  India
4  18.0       6.0          2968         140    2706         7.2     74     US

In [16]:
df.drop(['MPO'],axis=1,inplace=True)

In [17]:
df

   Cylinder  Displacement  Horsepower  weight  Accelarate  Model origin
1       4.0          1793         186    2196        15.9     73     US
2       8.0          1943         265    3527         8.3     80  India
4       6.0          2968         140    2706         7.2     74     US

In [18]:
df.drop(['Cylinder','Displacement'],axis=1,inplace=True)
df

   Horsepower  weight  Accelarate  Model origin
1         186    2196        15.9     73     US
2         265    3527         8.3     80  India
4         140    2706         7.2     74     US

In [22]:
df.drop(columns=['weight'],inplace=True)
df

   Horsepower  Accelarate  Model origin
1         186        15.9     73     US
2         265         8.3     80  India
4         140         7.2     74     US

In [24]:
df=df.drop(columns=['origin'])
df

   Horsepower  Accelarate  Model
1         186        15.9     73
2         265         8.3     80
4         140         7.2     74

# pop 
- we can reused the removed columns
- we can pop only one at the time

In [29]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [31]:
df.pop('car')

0       Ford
1     Jaguar
2       Audi
3    Hyundai
4       Tata
Name: car, dtype: str

In [32]:
df

,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,20.7,6.0,1823,247,3374,15.5,76,Japan
1,17.4,4.0,1793,186,2196,15.9,73,US
2,21.3,8.0,1943,265,3527,8.3,80,India
3,11.5,6.0,4498,196,3317,9.9,77,Germany
4,18.0,6.0,2968,140,2706,7.2,74,US

In [33]:
Cylinder=df.pop('Cylinder')
df

    MPO  Displacement  Horsepower  weight  Accelarate  Model   origin
0  20.7          1823         247    3374        15.5     76    Japan
1  17.4          1793         186    2196        15.9     73       US
2  21.3          1943         265    3527         8.3     80    India
3  11.5          4498         196    3317         9.9     77  Germany
4  18.0          2968         140    2706         7.2     74       US

In [34]:
Cylinder

0    6.0
1    4.0
2    8.0
3    6.0
4    6.0
Name: Cylinder, dtype: float64

# truncate

In [36]:
df

    MPO  Displacement  Horsepower  weight  Accelarate  Model   origin
0  20.7          1823         247    3374        15.5     76    Japan
1  17.4          1793         186    2196        15.9     73       US
2  21.3          1943         265    3527         8.3     80    India
3  11.5          4498         196    3317         9.9     77  Germany
4  18.0          2968         140    2706         7.2     74       US

In [51]:
df.truncate(2,3,axis=0)

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany

In [53]:
df=df.truncate(2,3,axis=0)

In [54]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany

In [56]:
df=df.truncate('MPO','Horsepower',axis=1)

ValueError: truncate requires a sorted index

In [64]:
df=df.sort_index(axis=1)
df

,Accelarate,Cylinder,Displacement,Horsepower,MPO,Model,car,origin,weight
2,8.3,8.0,1943,265,21.3,80,Audi,India,3527
3,9.9,6.0,4498,196,11.5,77,Hyundai,Germany,3317

In [65]:
df=df.truncate('Cylinder','Model',axis=1)
df

   Cylinder  Displacement  Horsepower   MPO  Model
2       8.0          1943         265  21.3     80
3       6.0          4498         196  11.5     77

In [62]:
df=df.sort_index(axis=1,ascending=False)
df

,weight,origin,car,Model,MPO,Horsepower,Displacement,Cylinder,Accelarate
2,3527,India,Audi,80,21.3,265,1943,8.0,8.3
3,3317,Germany,Hyundai,77,11.5,196,4498,6.0,9.9