In [1]:
import pandas as pd

In [39]:
df=pd.read_csv('../../../car_data_500.csv').head()
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [6]:
df['Horsepower']>200

0     True
1    False
2     True
3    False
4    False
Name: Horsepower, dtype: bool

In [10]:
df.loc[df['Horsepower']>200]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India

In [11]:
df['origin']=="Japan"

0     True
1    False
2    False
3    False
4    False
Name: origin, dtype: bool

In [12]:
df.loc[df['origin']=="Japan"]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan

In [13]:
df.loc[df['origin']=="japan"]

Empty DataFrame
Columns: [car, MPO, Cylinder, Displacement, Horsepower, weight, Accelarate, Model, origin]
Index: []

In [15]:
df['origin']=="japan"

0    False
1    False
2    False
3    False
4    False
Name: origin, dtype: bool

In [14]:
df['origin'].str.lower()=="japan"

0     True
1    False
2    False
3    False
4    False
Name: origin, dtype: bool

In [16]:
df.loc[df['origin'].str.lower()=="japan"]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan

In [6]:
df['Accelarate']>10

0     True
1     True
2    False
3    False
4    False
Name: Accelarate, dtype: bool

In [7]:
df[df['Accelarate']>10]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US

In [8]:
df['Model'] == 76

0     True
1    False
2    False
3    False
4    False
Name: Model, dtype: bool

In [10]:
df.loc[df['Model'] == 76]['car']

0    Ford
Name: car, dtype: str

In [12]:
df.loc[df['Model'] == 76][['car','origin']]

    car origin
0  Ford  Japan

In [13]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [15]:
df.filter(items=[1,3],axis=0)

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany

In [16]:
df.filter(items=['car','Cylinder'])

       car  Cylinder
0     Ford       6.0
1   Jaguar       4.0
2     Audi       8.0
3  Hyundai       6.0
4     Tata       6.0

In [17]:
df['origin'].str.contains('US')

0    False
1     True
2    False
3    False
4     True
Name: origin, dtype: bool

In [18]:
df[df['origin'].str.contains('US')]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [20]:
df['origin'].str.contains('us')

0    False
1    False
2    False
3    False
4    False
Name: origin, dtype: bool

In [21]:
df['origin'].str.contains('us' , case=False,na=False)
# case => change to case insensitive 
# na => avoid Null Value

0    False
1     True
2    False
3    False
4     True
Name: origin, dtype: bool

In [27]:
# Sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Email': ['alice@gmail.com', 'bob@yahoo.com', 'charlie@gmail.com', 'david@outlook.com']}
df = pd.DataFrame(data)

# Filter rows where Email ends with 'gmail.com'
# The regex pattern matches text ending with 'gmail.com'
gmail_df = df[df['Email'].str.contains(r'gmail\.com$', regex=True)]
print(gmail_df)

      Name              Email
0    Alice    alice@gmail.com
2  Charlie  charlie@gmail.com

In [40]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

## set index

In [41]:
df.set_index('origin')

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model
origin,,,,,,,,
Japan,Ford,20.7,6.0,1823,247,3374,15.5,76
US,Jaguar,17.4,4.0,1793,186,2196,15.9,73
India,Audi,21.3,8.0,1943,265,3527,8.3,80
Germany,Hyundai,11.5,6.0,4498,196,3317,9.9,77
US,Tata,18.0,6.0,2968,140,2706,7.2,74

In [43]:
df.columns

Index(['car', 'MPO', 'Cylinder', 'Displacement', 'Horsepower', 'weight',
       'Accelarate', 'Model', 'origin'],
      dtype='str')

In [44]:
df.columns.to_list()

['car',
 'MPO',
 'Cylinder',
 'Displacement',
 'Horsepower',
 'weight',
 'Accelarate',
 'Model',
 'origin']

In [37]:
df[df['Email'].str.contains('@g',regex='True')]

      Name              Email
0    Alice    alice@gmail.com
2  Charlie  charlie@gmail.com

In [45]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [46]:
df['origin']=="US"

0    False
1     True
2    False
3    False
4     True
Name: origin, dtype: bool

In [47]:
df['Model']==73

0    False
1     True
2    False
3    False
4    False
Name: Model, dtype: bool

In [48]:
(df['origin']=="US") & (df['Model']==73)

0    False
1     True
2    False
3    False
4    False
dtype: bool

In [49]:
df[(df['origin']=="US") & (df['Model']==73)]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US

In [51]:
df.loc[(df['Model']==76) | (df['Model']==74)]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [54]:
df.loc[(df['Model']==76)]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan

In [53]:
df.loc[~(df['Model']==76)]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [55]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [57]:
df.sort_values(by='car')

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [58]:
df.sort_values(by='car',ascending=False)

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India

In [66]:
df.sort_values(by=['origin','Cylinder'],ascending=[True,False])

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US

In [65]:
df.sort_values(by=['origin'])

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US