In [1]:
import pandas as pd

# Mathematical Operation
- add,sub,mul,div,mod,pow,Exponential(**),floor division on Both Dataframe & Series
- 2*2 /3*3 matrix

In [5]:
a=pd.DataFrame([
    [100,2,300],
    [4,5,6],
    [7,8,9]
])
a.columns=['x','y','z']
a

     x  y    z
0  100  2  300
1    4  5    6
2    7  8    9

In [6]:
b=pd.DataFrame([
    [10,2,30],
    [4,55,6],
    [1,8,9]
])
b.columns=['x','y','z']
b

    x   y   z
0  10   2  30
1   4  55   6
2   1   8   9

In [7]:
a+b

     x   y    z
0  110   4  330
1    8  60   12
2    8  16   18

In [8]:
a.add(b)

     x   y    z
0  110   4  330
1    8  60   12
2    8  16   18

In [9]:
a-b

    x   y    z
0  90   0  270
1   0 -50    0
2   6   0    0

In [12]:
a.sub(b)

    x   y    z
0  90   0  270
1   0 -50    0
2   6   0    0

In [13]:
a.subtract(b)

    x   y    z
0  90   0  270
1   0 -50    0
2   6   0    0

In [14]:
a*b

      x    y     z
0  1000    4  9000
1    16  275    36
2     7   64    81

In [15]:
a.mul(b)

      x    y     z
0  1000    4  9000
1    16  275    36
2     7   64    81

In [16]:
a.multiply(b)

      x    y     z
0  1000    4  9000
1    16  275    36
2     7   64    81

In [17]:
a/b

      x         y     z
0  10.0  1.000000  10.0
1   1.0  0.090909   1.0
2   7.0  1.000000   1.0

In [18]:
a//b

    x  y   z
0  10  1  10
1   1  0   1
2   7  1   1

In [19]:
a.floordiv(b)

    x  y   z
0  10  1  10
1   1  0   1
2   7  1   1

# Matrix Multiplication
- df1.dot(df2)
- df1 row Must Match with columns in df2
- 2* 3 /3* 2 Matrix

In [21]:
a=pd.DataFrame([
    [1,2,3],
    [2,5,4],
    
])
a

   0  1  2
0  1  2  3
1  2  5  4

In [22]:
b=pd.DataFrame([
    [1,3],
    [2,4],
    [5,7],
    
])
b

   0  1
0  1  3
1  2  4
2  5  7

In [24]:
a.dot(b)

    0   1
0  20  32
1  32  54

# Evaluate
- eval()
- we can give like expresstion eg: tot=price*qty as an argument

In [25]:
df=pd.DataFrame(
    [
        [200,1],
        [120,4],
        [23,10]
        
    ]
)
df.columns=['price','qty']
df

   price  qty
0    200    1
1    120    4
2     23   10

In [26]:
df.eval("Tot_amt = price*qty")

   price  qty  Tot_amt
0    200    1      200
1    120    4      480
2     23   10      230