In [1]:
import pandas as pd

# Function
- Custom Function (series,Dataframe) => .apply() eg: df.apply(custom_func)
  - NOTE: for dataframe need to mention pd.Series in function eg(def convert_function(column:pd.Series):)
  - column.str.lower().str.replace(' ','') for Chaining
    - assign() is used to create or update columns,
    - while apply() is used to modify values using a function
- Aggregate Function
    - sum,product,prod,mean,median,min,max,count,size,std,var
      - eg: for Dataframe: df.sum(numeric_only=True)
    - groupby eg: df['weight'].groupby(df['origin']).max()
        - df.groupby('origin').max(numeric_only=True)
        - df.groupby('origin')['weight'].max(numeric_only=True)
- unique()
- Map
  - interate with Every integer Element
  - apply
- Lambda
- Pipe (series / continous operation) .pipe().pipe()

In [28]:
df=pd.read_csv('../../../car_data_500.csv').head()
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [4]:
def convert_word(a):
    print( a.lower())
convert_word("WElocme")

welocme

In [18]:
def convert_word(a:str):
    if not isinstance(a,str):
        raise TypeError("Erorrrrrrrrr")
    print(a)
convert_word("WElocme")
convert_word(12)

WElocme

TypeError: Erorrrrrrrrr

In [6]:
def convert_word(a):
    return( a.lower())
df['origin'].apply(convert_word)

0      japan
1         us
2      india
3    germany
4         us
Name: origin, dtype: str

In [22]:
df_str=df[['car','origin']]
df_str

       car   origin
0     Ford    Japan
1   Jaguar       US
2     Audi    India
3  Hyundai  Germany
4     Tata       US

In [27]:
def convert_word(a):
    return( a.str.lower().str.upper())
df_str.apply(convert_word)

       car   origin
0     FORD    JAPAN
1   JAGUAR       US
2     AUDI    INDIA
3  HYUNDAI  GERMANY
4     TATA       US

In [3]:
def convert_kg_to_tonnes(weigth_kg):
    return weigth_kg/1000

def convert_hp_to_kw(hp):
    return hp*0.745

In [4]:
df.assign(tonnes=convert_kg_to_tonnes(df['weight']),
         kw=convert_hp_to_kw(df['Horsepower']))

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,tonnes,kw
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan,3.374,184.015
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US,2.196,138.570
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,3.527,197.425
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,3.317,146.020
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,2.706,104.300

In [16]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,origin_Max_weight
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan,3374
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US,2706
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,3527
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,3317
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,2706

In [6]:
df.sum()

car             FordJaguarAudiHyundaiTata
MPO                                  88.9
Cylinder                             30.0
Displacement                        13025
Horsepower                           1034
weight                              15120
Accelarate                           56.8
Model                                 380
origin              JapanUSIndiaGermanyUS
dtype: object

In [7]:
df.sum(numeric_only=True)

MPO                88.9
Cylinder           30.0
Displacement    13025.0
Horsepower       1034.0
weight          15120.0
Accelarate         56.8
Model             380.0
dtype: float64

In [10]:
df['weight'].groupby(df['origin']).max()

origin
Germany    3317
India      3527
Japan      3374
US         2706
Name: weight, dtype: int64

In [11]:
df.groupby('origin')['weight'].max(numeric_only=True)

origin
Germany    3317
India      3527
Japan      3374
US         2706
Name: weight, dtype: int64

In [12]:
df.groupby(['origin','Cylinder'])['weight'].max()

origin   Cylinder
Germany  6.0         3317
India    8.0         3527
Japan    6.0         3374
US       4.0         2196
         6.0         2706
Name: weight, dtype: int64

In [13]:
df.groupby(['origin','Cylinder'])[['weight','Displacement']].max()

                  weight  Displacement
origin  Cylinder
Germany 6.0         3317          4498
India   8.0         3527          1943
Japan   6.0         3374          1823
US      4.0         2196          1793
        6.0         2706          2968

In [18]:
df['origin_Max_weight']=df.groupby('origin')['weight'].transform('max')
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,origin_Max_weight
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan,3374
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US,2706
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,3527
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,3317
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,2706

In [19]:
df['origin'].unique()

<StringArray>
['Japan', 'US', 'India', 'Germany']
Length: 4, dtype: str

In [20]:
df['origin_map']=df['origin'].map({
    'US':101,
    'Japan':222,
    'India':333,
    'Germany':444
    
})
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,origin_Max_weight,origin_map
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan,3374,222
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US,2706,101
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,3527,333
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,3317,444
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,2706,101

In [24]:
a=[1,2,30,50,45]
b=[20,40,60,25,30]
c=[11,22,33,44,55]
df=pd.DataFrame(zip(a,b,c))
df.columns=['val1','val2','val3']
df

   val1  val2  val3
0     1    20    11
1     2    40    22
2    30    60    33
3    50    25    44
4    45    30    55

In [25]:
df=df.apply(lambda i:i*2)

In [26]:
df

   val1  val2  val3
0     2    40    22
1     4    80    44
2    60   120    66
3   100    50    88
4    90    60   110

In [30]:
df=pd.read_csv('../../../car_data_500.csv').head()

def convert_to_kw(hp):
    return hp*0.745

def fix_decimals(value):
    return round(value,2)
    
df['pipe_kw_dec']=df['Horsepower'].pipe(convert_to_kw).pipe(fix_decimals)

In [31]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,pipe_kw_dec
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan,184.02
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US,138.57
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,197.42
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,146.02
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,104.30