In [1]:
# Align DataFrame

In [1]:
import pandas as pd

# Align with Left join
- Aligning a DataFrame in Pandas means matching rows and Columns of two data Structures based on their labels(row index and column names)
- dataframe 1 (left) and dataframe 2 (right)  
- **Align-left** - Considers labels only available in Left Tables
- abc - cdef => abc c

In [3]:
df1=pd.DataFrame([[1,5,9],[5,2,10],[30,90,2]])
df1.columns=['A','B','C']
df1

    A   B   C
0   1   5   9
1   5   2  10
2  30  90   2

In [4]:
df2=pd.DataFrame([[9,10,5,2],[1,2,3,4],[9,7,4,1],[3,6,6,4]])
df2.columns=['C','D','E','F']
df2

   C   D  E  F
0  9  10  5  2
1  1   2  3  4
2  9   7  4  1
3  3   6  6  4

In [8]:
## 1. Align Based on Columns Label

In [11]:
left, right=df1.align(df2,join='left')

In [12]:
left

    A   B   C
0   1   5   9
1   5   2  10
2  30  90   2

In [13]:
right

    A   B  C
0 NaN NaN  9
1 NaN NaN  1
2 NaN NaN  9

In [14]:
## 2.  Align Based on Row Index

In [15]:
left, right=df1.align(df2,join='left',axis=0)

In [16]:
left

    A   B   C
0   1   5   9
1   5   2  10
2  30  90   2

In [17]:
right

   C   D  E  F
0  9  10  5  2
1  1   2  3  4
2  9   7  4  1

In [18]:
# Align with Right join

In [20]:
left , right=df1.align(df2,join='right')

In [21]:
left

      C   D   E   F
0   9.0 NaN NaN NaN
1  10.0 NaN NaN NaN
2   2.0 NaN NaN NaN
3   NaN NaN NaN NaN

In [22]:
right

   C   D  E  F
0  9  10  5  2
1  1   2  3  4
2  9   7  4  1
3  3   6  6  4

In [23]:
left , right=df1.align(df2,join='right' , axis=0)

In [24]:
left

      A     B     C
0   1.0   5.0   9.0
1   5.0   2.0  10.0
2  30.0  90.0   2.0
3   NaN   NaN   NaN

In [25]:
right

   C   D  E  F
0  9  10  5  2
1  1   2  3  4
2  9   7  4  1
3  3   6  6  4

In [28]:
## Align with Inner join

In [30]:
left , right =df1.align(df2,join='inner')

In [27]:
left

    C
0   9
1  10
2   2

In [31]:
right

   C
0  9
1  1
2  9

In [39]:
left , right =df1.align(df2,join='inner',axis=0)

In [40]:
left

    A   B   C
0   1   5   9
1   5   2  10
2  30  90   2

In [41]:
right

   C   D  E  F
0  9  10  5  2
1  1   2  3  4
2  9   7  4  1

In [32]:
## Align with Outer join

In [33]:
left,right= df1.align(df2,join='outer')

In [34]:
left

      A     B     C   D   E   F
0   1.0   5.0   9.0 NaN NaN NaN
1   5.0   2.0  10.0 NaN NaN NaN
2  30.0  90.0   2.0 NaN NaN NaN
3   NaN   NaN   NaN NaN NaN NaN

In [35]:
right

    A   B  C   D  E  F
0 NaN NaN  9  10  5  2
1 NaN NaN  1   2  3  4
2 NaN NaN  9   7  4  1
3 NaN NaN  3   6  6  4

In [36]:
left,right= df1.align(df2,join='outer',axis=0)

In [37]:
left

      A     B     C
0   1.0   5.0   9.0
1   5.0   2.0  10.0
2  30.0  90.0   2.0
3   NaN   NaN   NaN

In [38]:
right

   C   D  E  F
0  9  10  5  2
1  1   2  3  4
2  9   7  4  1
3  3   6  6  4