In [1]:
import pandas as pd

In [2]:
# concatenate (join vertical)

In [23]:
df1=pd.DataFrame(
    [
        [1,5],
        [5,2]
    ]
)
df1.columns=['A','B']
df1

   A  B
0  1  5
1  5  2

In [17]:
df2=pd.DataFrame([
    [12,5],
    [1,4]
])
df2.columns=['A','B']
df2

    A  B
0  12  5
1   1  4

In [5]:
##  Concatenate with same Column Names

In [18]:
pd.concat([df1,df2])

    A  B
0   1  5
1   5  2
0  12  5
1   1  4

In [7]:
## Concatenate with Various Column Names

In [24]:
df3=pd.DataFrame(
    [[12,5],
    [1,4]]
)
df3.columns=['B','C']
df3

    B  C
0  12  5
1   1  4

In [20]:
pd.concat([df1,df3])

     A   B    C
0  1.0   5  NaN
1  5.0   2  NaN
0  NaN  12  5.0
1  NaN   1  4.0

## Joining with Various Column Names (horizonal)

In [27]:
df1.join(df2,lsuffix="_one",rsuffix="_two")

   A_one  B_one  A_two  B_two
0      1      5     12      5
1      5      2      1      4

## Joining with same Column Names

In [28]:
df1.join(df3,lsuffix="_one",rsuffix="_two")

   A  B_one  B_two  C
0  1      5     12  5
1  5      2      1  4