In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('../../../car_data_500.csv')
df_head=df.head()
df_head

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

# Ranking

**Top 3 cars Bsed on weight**

In [6]:
df_head.nlargest(3,'weight')

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany

In [7]:
]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

## Ranking Row

In [8]:
df_head['Rank']=df_head['Accelarate'].rank(method='first')

In [11]:
df_head.sort_values('Rank').head(3)

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,Rank
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,1.0
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,2.0
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,3.0

In [13]:
df_head['Rank']=df_head['Accelarate'].rank(method='min')  
df_head
# 2 number same na take same number skip the next number -> for next takes min value 
# 11 345 66 8

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,Rank
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan,4.0
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US,5.0
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,2.0
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,3.0
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,1.0

In [14]:
df_head['Rank']=df_head['Accelarate'].rank(method='max')  
df_head
# 2 number same na take same number skip the next number -> for next takes min value 
# 2 2 3 skip 1st rank takes 2

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,Rank
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan,4.0
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US,5.0
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,2.0
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,3.0
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,1.0

In [25]:
df_head['Rank']=df_head['Cylinder'].rank(method='dense')  
df_head=df_head.sort_values('Rank')
# 2 number same na take same number skip the next number -> for next takes min value 
# 1,1,1,2,2,2,3,3,3

In [26]:
df_head

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,Rank
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US,1.0
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,2.0
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan,2.0
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,2.0
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,3.0

In [27]:
df_head[df_head['Rank']<=3]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin,Rank
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US,1.0
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US,2.0
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan,2.0
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany,2.0
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India,3.0

In [24]:
df_head[df_head['Rank']<=3].shape

(3, 10)

# Relationship Analysis

## 1. Covariance - how one Variable move with Other Variable in terms of Direction
- height incr -> weight incr => Positive
- height incr -> weight decr => Negative

In [31]:
df['Horsepower'].cov(df['weight'])
# just check positive or negative 
# (+) both increase

np.float64(1349.3491783567142)

## 2. Correlation - how two variables related together? in Values & direction

In [35]:
df['Horsepower'].corr(df['weight'])*100
# both incr
# to check with percentage ( *100)

np.float64(2.69853384542212)

## 3. Correlation with - compare a variable with a Dataframe

In [40]:
x=df.select_dtypes(include='number').drop(columns='weight')
y=df['weight']

In [41]:
x.corrwith(y)

MPO            -0.018206
Cylinder        0.039982
Displacement    0.048320
Horsepower      0.026985
Accelarate      0.002681
Model           0.014515
dtype: float64

## Autocorr - how a value relate to previous value | Time Series
*EG: Time Based values=> current temperature  15deg c previous la 14 degcelsius

In [59]:
df=pd.read_csv('../../../date_temperature_50rows.csv')
df=df.head()
df

         Date  Temperature
0  2026-01-01        25.35
1  2026-01-02        25.31
2  2026-01-03        25.98
3  2026-01-04        27.22
4  2026-01-05        27.04

In [60]:
df['Temperature'].autocorr()*100

np.float64(72.94800869939728)

# Trend Analysis

## 1. Difference Between Previous Values

In [62]:
df['Difference']=df['Temperature'].diff()
df

         Date  Temperature  Difference
0  2026-01-01        25.35         NaN
1  2026-01-02        25.31       -0.04
2  2026-01-03        25.98        0.67
3  2026-01-04        27.22        1.24
4  2026-01-05        27.04       -0.18

In [63]:
## 2.Percentage

In [66]:
df['Percentage change']=df['Temperature'].pct_change()
df

         Date  Temperature  Difference  Percentage change
0  2026-01-01        25.35         NaN                NaN
1  2026-01-02        25.31       -0.04          -0.001578
2  2026-01-03        25.98        0.67           0.026472
3  2026-01-04        27.22        1.24           0.047729
4  2026-01-05        27.04       -0.18          -0.006613

# Cumulative Operation

In [69]:
df_courses=pd.DataFrame([['22C01','C#',6000],['22C02','C++',9000],['22C03','Dart',6000],['22C04','Flutter',18000],['22C05','java',6000]])
df_courses.columns=["ID","Name","fee"]
df_courses

      ID     Name    fee
0  22C01       C#   6000
1  22C02      C++   9000
2  22C03     Dart   6000
3  22C04  Flutter  18000
4  22C05     java   6000

In [70]:
df_payment=pd.DataFrame([['22C001','2022-01-02','22S001','22C15',1000],['22C002','2022-01-02','22S001','22C12',8000],['22C003','2022-01-09','22S002','22C02',1000],['22C004','2022-01-09','22S002','22C03',7000],['22C005','2022-01-09','22S002','22C02',5000]])
df_payment.columns=['Transaction','Data','Student','Course','Paid']
df_payment

  Transaction        Data Student Course  Paid
0      22C001  2022-01-02  22S001  22C15  1000
1      22C002  2022-01-02  22S001  22C12  8000
2      22C003  2022-01-09  22S002  22C02  1000
3      22C004  2022-01-09  22S002  22C03  7000
4      22C005  2022-01-09  22S002  22C02  5000

## Running Sum

In [74]:
# Find the Total Sales
df_payment['Running Sum']=df_payment['Paid'].cumsum()
df_payment

  Transaction        Data Student Course  Paid  Running Sum
0      22C001  2022-01-02  22S001  22C15  1000         1000
1      22C002  2022-01-02  22S001  22C12  8000         9000
2      22C003  2022-01-09  22S002  22C02  1000        10000
3      22C004  2022-01-09  22S002  22C03  7000        17000
4      22C005  2022-01-09  22S002  22C02  5000        22000

In [76]:
# Running Max | Cumulative MAX

In [82]:
df_payment['Max sales']=df_payment['Paid'].cummax()
df_payment

,Transaction,Data,Student,Course,Paid,Running Sum,Max sales,Min sales
0,22C001,2022-01-02,22S001,22C15,1000,1000,1000,1000
1,22C002,2022-01-02,22S001,22C12,8000,9000,8000,1000
2,22C003,2022-01-09,22S002,22C02,1000,10000,8000,1000
3,22C004,2022-01-09,22S002,22C03,7000,17000,8000,1000
4,22C005,2022-01-09,22S002,22C02,5000,22000,8000,1000

In [83]:
# Running Min | Cumulative Min

In [84]:
df_payment['Min sales']=df_payment['Paid'].cummin()
df_payment

,Transaction,Data,Student,Course,Paid,Running Sum,Max sales,Min sales
0,22C001,2022-01-02,22S001,22C15,1000,1000,1000,1000
1,22C002,2022-01-02,22S001,22C12,8000,9000,8000,1000
2,22C003,2022-01-09,22S002,22C02,1000,10000,8000,1000
3,22C004,2022-01-09,22S002,22C03,7000,17000,8000,1000
4,22C005,2022-01-09,22S002,22C02,5000,22000,8000,1000