In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('../../../car_data_500.csv').head(15)

## 1. Uniqueness

**List out all the Countries - do not Repeat Country Name**

In [4]:
df['origin'].unique()

<StringArray>
['Japan', 'US', 'India', 'Germany', 'South Korea']
Length: 5, dtype: str

## 2. Number of Unique Value
**Total number of countries -do not Repeat Country name**

In [5]:
df['origin'].nunique()

5

## 3. Count Values in Each Group
**How many car each country consists of?**

In [6]:
df['origin'].value_counts()

origin
South Korea    6
US             4
Japan          2
India          2
Germany        1
Name: count, dtype: int64

**Present in Percentage**

In [1]:
df['origin'].value_counts(normalize=True)*100 # to get Average

NameError: name 'df' is not defined

# Duplicate

**1. How many rows are Duplicate**

In [24]:
df.duplicated().sum() # no Duplicate na 0

np.int64(0)

## Remove Duplicate
**Remove Duplicate Rows**

In [28]:
df.drop_duplicates().head() # return new Dataframe 
# df=df.drop_duplicates()
# df.drop_duplicates(inplace=True)

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

# Central Tendancy

1. Mean (sum/Total)
2. Median (middle value) -> sort-> center value (If its Even (sum of 2 mid values/2))
3. Mode (Most Frequent Value )

**Mean**

In [30]:
df['weight'].mean()

np.float64(3021.2)

In [31]:
df['weight'].median()

np.float64(3156.0)

In [35]:
df_head=df.head()
df_head

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [40]:
df_head['origin'].mode()

0    US
Name: origin, dtype: str

# Statistical Analysis

In [42]:
df_stat=df.head()
df_stat

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

**What's the range of data**

In [45]:
# min Value
df['weight'].min()

np.int64(1800)

In [47]:
#max value
df['weight'].max()

np.int64(4292)

In [48]:
# Average
df['weight'].mean()

np.float64(3021.2)

## how data Spread from mean?
how its spread from Center

In [50]:
# Variance 
df['weight'].var()

np.float64(637738.7428571429)

In [52]:
#standard Deviation
df['weight'].std()

np.float64(798.5854637151511)

## how Data Balanced from mean?

# Skew
Skewness-ன் 3 முக்கிய வகைகள்:
- Positive Skew (வலது பக்கம் சாய்ந்தது / Right-skewed):
    - விளக்கம்: வரைபடத்தின் நீண்ட வால் (long tail) வலது பக்கமாக நீண்டு இருக்கும்.
    - பெரும்பாலான டேட்டாக்கள் இடது பக்கத்தில் (சிறிய மதிப்புகளில்) குவிந்திருக்கும்.
    - விகிதம்: இதில் சராசரி (Mean) ஆனது மீடியனை (Median) விட அதிகமாக இருக்கும் (Mean > Median).
    - **நிஜ உலக உதாரணம்:** மக்களின் வருமானம் (Income).
   - ஒரு நாட்டின் பெரும்பாலான மக்கள் நடுத்தர அல்லது குறைந்த வருமானமே ஈட்டுவர் (இடது பக்க குவிப்பு). ஆனால், ஒரு சில கோடீஸ்வரர்களின் அதீத வருமானம் இந்த வரைபடத்தை வலது பக்கமாக இழுத்து ஒரு நீண்ட வாலை உருவாக்கும்.
- Negative Skew (இடது பக்கம் சாய்ந்தது / Left-skewed):
   - விளக்கம்: வரைபடத்தின் நீண்ட வால் (long tail) இடது பக்கமாக நீண்டு இருக்கும்.
   - பெரும்பாலான டேட்டாக்கள் வலது பக்கத்தில் (பெரிய மதிப்புகளில்) குவிந்திருக்கும்.
   - விகிதம்: இதில் சராசரி (Mean) ஆனது மீடியனை (Median) விட குறைவாக இருக்கும் (Mean < Median).
   - **நிஜ உலக உதாரணம்:** மனிதர்கள் ஓய்வு பெறும் வயது (Retirement Age).
   - பெரும்பாலான மக்கள் தங்கள் 60 அல்லது 65 வயதில் ஓய்வு பெறுவார்கள் (வலது பக்க குவிப்பு).
   - ஆனால், மிகச் சிலரே தங்களின் 30 அல்லது 40 வயதிலேயே ஓய்வு பெறுவர்.
   - இந்த ஆரம்பகால ஓய்வு வரைபடத்தை இடது பக்கமாக இழுக்கும்.
- Zero Skew (சமச்சீர் நிலை / Symmetric):
   - விளக்கம்: வரைபடம் இடதும் வலதும் சரியாக சமமாக இருக்கும். எந்தப் பக்கமும் சாயாது.
   - விகிதம்: இதில் Mean, Median, Mode ஆகிய மூன்றும் ஒரே புள்ளியில் இருக்கும் (Mean = Median = Mode).
   - **நிஜ உலக உதாரணம்:** மனிதர்களின் உயரம் (Height). ஒரு குறிப்பிட்ட வயதில் உள்ள மனிதர்களின் உயரத்தை அளந்தால், பெரும்பாலானோர் சராசரி உயரத்திலும், மிகச் சிலரே மிகக் குட்டையாகவோ அல்லது மிக உயரமகவோ இருப்பார்கள்.

In [53]:
#skewness how data is distributed
df['weight'].skew()
# near to 0 distributed Evenly 
# (+ ) Right la skew
# (-) left side la skew

np.float64(-0.13215680992312545)

## how extreme the outliers are?
Extremely Rare condition-(Eg: age > 120 its not normal but people live 120 years)

# kurtosis
- 1. Leptokurtic (உயரமான கோபுரம் & தடிமனான வால் - High Kurtosis):
    - விளக்கம்: இதன் நடுப்பகுதி மிகவும் உயரமாக இருக்கும். அதே சமயம், அதன் இரு பக்கவாட்டு வால்கள் (tails) மிகவும் தடிமனாக இருக்கும்.
    - பொருள்: இதில் எதிர்பாராத, மிக விசித்திரமான சம்பவங்கள் (extreme outliers) அதிகமாக நடக்கும்.
    - உதாரணம்: பங்குச் சந்தை (Stock Market). பொதுவாகப் பங்கு விலை பெரிய மாற்றம் இல்லாமல் இருக்கும் (உயரமான நடுப்பகுதி). 
        - ஆனால், திடீரென ஒரு நாள் பெரும் வீழ்ச்சியோ அல்லது மிகப்பெரிய லாபமோ (Fat tails) ஏற்படும்
- 2.Platykurtic (தட்டையான வடிவம் & மெல்லிய வால் - Low Kurtosis)
  - விளக்கம்: இது பார்க்க மிகவும் தட்டையாக (flat) இருக்கும். இதன் பக்கவாட்டு வால்கள் மிகவும் மெலிதாக இருக்கும் அல்லது வால்களே இருக்காது.
  - பொருள்: இதில் அதீத விளிம்பு நிலை மாற்றங்கள் (outliers) இருக்காது. டேட்டா அனைத்தும் பரவலாக சமமாக இருக்கும்.
  - உதாரணம்: ஒரு பகடையை (Dice) உருட்டுவது. நீங்கள் 1000 முறை பகடையை உருட்டினால் 1, 2, 3, 4, 5, 6 ஆகிய அனைத்து எண்களும் தோராயமாக சமமான முறையே விழும். இதனால் வரைபடம் தட்டையாக இருக்கும். 7 விழ வாய்ப்பே இல்லை என்பதால் வால்கள் இருக்காது
- Mesokurtic (சாதாரண நிலை - Normal Distribution):
  - விளக்கம்: இது சரியான அளவில் இருக்கும் ஒரு பெல் கர்வ் (Normal bell curve).
  - பொருள்: இதன் Kurtosis மதிப்பு சரியாக 3 ஆக இருக்கும் (Excess Kurtosis = 0)

In [54]:
# kurtosis
df['weight'].kurt() 
# (-)  Less
# (0) no 
# (+) High Kurtosis

np.float64(-1.1885919033945709)

## how values Distributed across Dataset

In [57]:
# 50% of data Distribution
df['weight'].quantile()

np.float64(3156.0)

In [58]:
# 25% of Data Distribution
df['weight'].quantile(.25)

np.float64(2319.0)

In [59]:
# 75% of Data Distribution 
df['weight'].quantile(.75)

np.float64(3639.5)

In [60]:
df['weight'].describe()

count      15.000000
mean     3021.200000
std       798.585464
min      1800.000000
25%      2319.000000
50%      3156.000000
75%      3639.500000
max      4292.000000
Name: weight, dtype: float64