In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('car_data.txt').head()
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374.0,15.5,76,NaN
1,Jaguar,17.4,4.0,1793,186,NaN,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527.0,8.3,80,India
3,Hyundai,11.5,NaN,4498,196,3317.0,9.9,77,Germany
4,Tata,18.0,NaN,2968,140,2706.0,7.2,74,US

In [5]:
df.isna() # true if null value Present

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False

In [6]:
df.isna().sum() #Based on Columnwise

car             0
MPO             0
Cylinder        0
Displacement    0
Horsepower      0
weight          0
Accelarate      0
Model           0
origin          0
dtype: int64

In [7]:
df.isnull()
# df.isnull().sum()

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False

In [8]:
# Filter missing Values
df.loc[df['Horsepower'].isna()]

Empty DataFrame
Columns: [car, MPO, Cylinder, Displacement, Horsepower, weight, Accelarate, Model, origin]
Index: []

# Handle Missing Value

## Drop missing Records

In [9]:
df.dropna()
# df =df.dropna()
# df.dropna(inplace=True)

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [10]:
df.shape

(5, 9)

In [11]:
df.fillna(value=1000)

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374,15.5,76,Japan
1,Jaguar,17.4,4.0,1793,186,2196,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527,8.3,80,India
3,Hyundai,11.5,6.0,4498,196,3317,9.9,77,Germany
4,Tata,18.0,6.0,2968,140,2706,7.2,74,US

In [12]:

# fill 1000
df.loc[df['Cylinder']==1000]

Empty DataFrame
Columns: [car, MPO, Cylinder, Displacement, Horsepower, weight, Accelarate, Model, origin]
Index: []