In [1]:
import pandas as pd

In [23]:
df=pd.read_csv('car_data.txt').head()
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374.0,15.5,76,NaN
1,Jaguar,17.4,4.0,1793,186,NaN,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527.0,8.3,80,India
3,Hyundai,11.5,NaN,4498,196,3317.0,9.9,77,Germany
4,Tata,18.0,NaN,2968,140,2706.0,7.2,74,US

In [3]:
df.isna() # true if null value Present

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,True,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False

In [4]:
df.isna().sum() #Based on Columnwise

car             0
MPO             0
Cylinder        2
Displacement    0
Horsepower      0
weight          1
Accelarate      0
Model           0
origin          1
dtype: int64

In [5]:
df.isnull()
# df.isnull().sum()

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,True,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False

In [8]:
# Filter missing Values
df.loc[df['Horsepower'].isna()]

Empty DataFrame
Columns: [car, MPO, Cylinder, Displacement, Horsepower, weight, Accelarate, Model, origin]
Index: []

# Handle Missing Value

## Drop missing Records

In [6]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374.0,15.5,76,NaN
1,Jaguar,17.4,4.0,1793,186,NaN,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527.0,8.3,80,India
3,Hyundai,11.5,NaN,4498,196,3317.0,9.9,77,Germany
4,Tata,18.0,NaN,2968,140,2706.0,7.2,74,US

In [7]:
df.dropna()
# df =df.dropna()
# df.dropna(inplace=True)

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
2,Audi,21.3,8.0,1943,265,3527.0,8.3,80,India

In [10]:
df.shape

(5, 9)

In [20]:
df=df.fillna(value=1000)

In [21]:
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374.0,15.5,76,1000
1,Jaguar,17.4,4.0,1793,186,1000.0,15.9,73,US
2,Audi,21.3,8.0,1943,265,3527.0,8.3,80,India
3,Hyundai,11.5,1000.0,4498,196,3317.0,9.9,77,Germany
4,Tata,18.0,1000.0,2968,140,2706.0,7.2,74,US

In [22]:
df.loc[df['origin']==1000]

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,1823,247,3374.0,15.5,76,1000

In [31]:
df=pd.read_csv('car_data.csv').head(10)
df

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,NaN,NaN,3374.0,15.5,76,NaN
1,Jaguar,17.4,4.0,1793.0,186.0,NaN,15.9,73,US
2,Audi,21.3,8.0,NaN,265.0,NaN,8.3,80,India
3,Hyundai,NaN,NaN,4498.0,NaN,3317.0,NaN,77,NaN
4,Toyota,18.0,NaN,NaN,140.0,2706.0,7.2,74,US
5,Kia,15.7,NaN,2659.0,155.0,3156.0,10.2,76,US
6,Toyota,16.9,8.0,3148.0,102.0,3974.0,15.5,79,NaN
7,Ford,19.1,8.0,4693.0,150.0,1800.0,12.7,72,NaN
8,BMW,17.5,6.0,3801.0,221.0,1818.0,10.8,76,South Korea
9,Tata,18.1,6.0,3268.0,130.0,2383.0,11.1,80,India

In [32]:
df.dropna()

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
8,BMW,17.5,6.0,3801.0,221.0,1818.0,10.8,76,South Korea
9,Tata,18.1,6.0,3268.0,130.0,2383.0,11.1,80,India

In [33]:
df.dropna(how="any")

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
8,BMW,17.5,6.0,3801.0,221.0,1818.0,10.8,76,South Korea
9,Tata,18.1,6.0,3268.0,130.0,2383.0,11.1,80,India

In [34]:
df.dropna(how="all")

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,NaN,NaN,3374.0,15.5,76,NaN
1,Jaguar,17.4,4.0,1793.0,186.0,NaN,15.9,73,US
2,Audi,21.3,8.0,NaN,265.0,NaN,8.3,80,India
3,Hyundai,NaN,NaN,4498.0,NaN,3317.0,NaN,77,NaN
4,Toyota,18.0,NaN,NaN,140.0,2706.0,7.2,74,US
5,Kia,15.7,NaN,2659.0,155.0,3156.0,10.2,76,US
6,Toyota,16.9,8.0,3148.0,102.0,3974.0,15.5,79,NaN
7,Ford,19.1,8.0,4693.0,150.0,1800.0,12.7,72,NaN
8,BMW,17.5,6.0,3801.0,221.0,1818.0,10.8,76,South Korea
9,Tata,18.1,6.0,3268.0,130.0,2383.0,11.1,80,India

In [35]:
df.dropna(thresh=5)

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
0,Ford,20.7,6.0,NaN,NaN,3374.0,15.5,76,NaN
1,Jaguar,17.4,4.0,1793.0,186.0,NaN,15.9,73,US
2,Audi,21.3,8.0,NaN,265.0,NaN,8.3,80,India
4,Toyota,18.0,NaN,NaN,140.0,2706.0,7.2,74,US
5,Kia,15.7,NaN,2659.0,155.0,3156.0,10.2,76,US
6,Toyota,16.9,8.0,3148.0,102.0,3974.0,15.5,79,NaN
7,Ford,19.1,8.0,4693.0,150.0,1800.0,12.7,72,NaN
8,BMW,17.5,6.0,3801.0,221.0,1818.0,10.8,76,South Korea
9,Tata,18.1,6.0,3268.0,130.0,2383.0,11.1,80,India

In [37]:
df.dropna(thresh=8)

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
1,Jaguar,17.4,4.0,1793.0,186.0,NaN,15.9,73,US
5,Kia,15.7,NaN,2659.0,155.0,3156.0,10.2,76,US
6,Toyota,16.9,8.0,3148.0,102.0,3974.0,15.5,79,NaN
7,Ford,19.1,8.0,4693.0,150.0,1800.0,12.7,72,NaN
8,BMW,17.5,6.0,3801.0,221.0,1818.0,10.8,76,South Korea
9,Tata,18.1,6.0,3268.0,130.0,2383.0,11.1,80,India

In [41]:
df.dropna(subset=['origin'])

,car,MPO,Cylinder,Displacement,Horsepower,weight,Accelarate,Model,origin
1,Jaguar,17.4,4.0,1793.0,186.0,NaN,15.9,73,US
2,Audi,21.3,8.0,NaN,265.0,NaN,8.3,80,India
4,Toyota,18.0,NaN,NaN,140.0,2706.0,7.2,74,US
5,Kia,15.7,NaN,2659.0,155.0,3156.0,10.2,76,US
8,BMW,17.5,6.0,3801.0,221.0,1818.0,10.8,76,South Korea
9,Tata,18.1,6.0,3268.0,130.0,2383.0,11.1,80,India