In [1]:
import pandas as pd

In [2]:
df1=pd.DataFrame([[1,5,9],[5,2,10],[30,90,2]])
df1.columns=['A','B','C']
df1

    A   B   C
0   1   5   9
1   5   2  10
2  30  90   2

In [3]:
df2=pd.DataFrame([[9,10,5,2],[1,2,3,4],[9,7,4,1],[3,6,6,4]])
df2.columns=['C','D','E','F']
df2

   C   D  E  F
0  9  10  5  2
1  1   2  3  4
2  9   7  4  1
3  3   6  6  4

In [4]:
left, right=df1.align(df2,join='left')

In [5]:
left

    A   B   C
0   1   5   9
1   5   2  10
2  30  90   2

In [16]:
right

    A   B  C   D  E  F
0 NaN NaN  9  10  5  2
1 NaN NaN  1   2  3  4
2 NaN NaN  9   7  4  1
3 NaN NaN  3   6  6  4

In [18]:
left, right=df1.align(df2,join='left',axis=0)

In [19]:
left

    A   B   C
0   1   5   9
1   5   2  10
2  30  90   2

In [20]:
right

   C   D  E  F
0  9  10  5  2
1  1   2  3  4
2  9   7  4  1

In [7]:
left, right=df1.align(df2,join='right')

In [8]:
left

      C   D   E   F
0   9.0 NaN NaN NaN
1  10.0 NaN NaN NaN
2   2.0 NaN NaN NaN
3   NaN NaN NaN NaN

In [9]:
right

   C   D  E  F
0  9  10  5  2
1  1   2  3  4
2  9   7  4  1
3  3   6  6  4

In [10]:
left, right=df1.align(df2,join='inner')

In [11]:
left

    C
0   9
1  10
2   2

In [12]:
right

   C
0  9
1  1
2  9

In [13]:
left, right=df1.align(df2,join='outer')

In [14]:
left

      A     B     C   D   E   F
0   1.0   5.0   9.0 NaN NaN NaN
1   5.0   2.0  10.0 NaN NaN NaN
2  30.0  90.0   2.0 NaN NaN NaN
3   NaN   NaN   NaN NaN NaN NaN

In [15]:
right

    A   B  C   D  E  F
0 NaN NaN  9  10  5  2
1 NaN NaN  1   2  3  4
2 NaN NaN  9   7  4  1
3 NaN NaN  3   6  6  4

In [21]:
df1=pd.DataFrame(
    [
        [1,5],
        [5,2]
    ]
)
df1.columns=['A','B']
df1

   A  B
0  1  5
1  5  2

In [25]:
df2=pd.DataFrame([
    [12,5],
    [1,4]
])
df2.columns=['A','B']
df2

    A  B
0  12  5
1   1  4

In [26]:
pd.concat([df1,df2])

    A  B
0   1  5
1   5  2
0  12  5
1   1  4

In [29]:
df3=pd.DataFrame([
    [12,5],
    [1,4]
])
df3.columns=['A','C']
df3

    A  C
0  12  5
1   1  4

In [32]:
df4=pd.DataFrame([
    [121,51],
    [11,41]
])
df3.columns=['B','D']
df3

    B  D
0  12  5
1   1  4

In [28]:
pd.concat([df1,df3])

    A    B    c
0   1  5.0  NaN
1   5  2.0  NaN
0  12  NaN  5.0
1   1  NaN  4.0

In [33]:
df3.join(df4)

    B  D    0   1
0  12  5  121  51
1   1  4   11  41

In [35]:
df1.join(df2,rsuffix='_right')

   A  B  A_right  B_right
0  1  5       12        5
1  5  2        1        4